### ISSUE TITLE
small typo (I think)

### ISSUE THREAD

**Issue by hotemetoot** [cityofaustin/knackpy#11]
Hi. I found what seems to be a typo in the instructions for retrieving data directly from an object. There is no comma aftert the line "obj ='object_1'"

```
>>> kn = Knack(
      obj='object_1'
      app_id='abc123',
      api_key='topsecretapikey'
    )
```
Anyhow, thanks so mych for writing this! It is really fantastic for backing up data and also for integrating Knack with Power BI.

**Comment by johnclary** [comment]
Thanks for finding that, and for the positive feedback. I see a few other errors in the docs. Will fix for the next release. Feel free to submit a PR in the meantime ;)
