### ISSUE TITLE
get_app_data does not correctly handle 502 error

### ISSUE THREAD

**Issue by geoandrew** [cityofaustin/knackpy#16]
Knack is down at the moment and sending this request: "https://loader.knack.com/v1/applications/my app id" Gives a 502 error.

Calling knackpy.get_app_data(<my app id>) throws an exception:
```
knack_app_info = get_app_data(knack_app_id)
  File "...../python3.6/site-packages/knackpy/__init__.py", line 516, in get_app_data
    raise Exception(req.text)
NameError: name 'req' is not defined
```
Need to fix the error handling to cover this case.

**Comment by johnclary** [comment]
Good catch @geoandrew. Thanks--and feel free to submit a PR ;)

**Comment by geoandrew** [comment]
I do hope to get to this  ;-)

**Comment by johnclary** [comment]
Will be fixed in [`v1.0`](https://github.com/cityofaustin/knackpy/tree/v1.0.0/knackpy)

**Comment by johnclary** [comment]
We don't have a specific test for this (because it's hard to force the error), but i've come across `502`'s while developing and the error is raised as expected.

**Comment by johnclary** [comment]
[Closing](https://github.com/cityofaustin/knackpy/releases/tag/v1.0.9).
