### ISSUE TITLE
Help with dates

### ISSUE THREAD

**Issue by CatParky** [cityofaustin/knackpy#17]
Hi,
Is there anyway of returning a specific format of date ? 
My object has calculated dates and user entry and both fields return different formats eg.

- Calculated field returns UNIX/Epoch value : 1576735200000

- User entry field returns all fomatting options : {'date': '12/19/2019', 'date_formatted': '19/12/2019', 'hours': '12', 'minutes': '00', 'am_pm': 'AM', 'unix_timestamp': 1576713600000, 'iso_timestamp': '2019-12-19T00:00:00.000Z', 'timestamp': '12/19/2019 12:00 am', 'time': 0}

Ideally I would like both to return a specified format (preferably UK formatted ddmmyyyy or ISO yyyymmdd)

Thank you for creating this
(pls note I am a brand new user to python so apologies if this request makes no sense)

**Comment by johnclary** [comment]
@CatParky this is logic that you'll need to write outside of `knackpy`. You should do some research to become familiar with date parsing and formatting in python. There are lots of libraries that can help you do this. Consider [arrow](https://arrow.readthedocs.io/en/latest/).
