### ISSUE TITLE
Address field subfield "street_2" missing

### ISSUE THREAD

**Issue by CatParky** [cityofaustin/knackpy#28]
When I interact with a field that contains an address it does not return the Street_2 value that is available in the api. When looking at section of the code that deals with subfields it only lists :
if field_type == 'address':
                        for subfield in ('latitude', 'longitude', 'formatted_value',
                                         'street', 'city', 'state', 'country', 'zip'):

Please can the value for street_2 be added ?

**Comment by johnclary** [comment]
thanks @CatParky. i intend to address this in the next month or so. feel free to submit a PR as well.

**Comment by johnclary** [comment]
@CatParky good news. this is available now with `v0.1.0`.
