### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by CatParky** [cityofaustin/knackpy#32]
Hi,
I get the following errors under specific circumstances 

> Traceback (most recent call last):
  File "Z:\System Administrator\System Backups\xxxxxx\Scripts\KNACK OpsManager - Test.py", line 26, in <module> 
    rows_per_page=1000
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\knackpy\knackpy.py", line 155, in __init__
    self.data = self._parse_data()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\knackpy\knackpy.py", line 408, in _parse_data
    dt_utc = datetime.utcfromtimestamp(d / 1000)
OSError: [Errno 22] Invalid argument

I have tried running various stripped down scripts and found that this works 
```
from knackpy import Knack
kn = Knack( 
        obj='object_1',     
        app_id='XXXXXX',
        api_key='XXXXXX',
        tzinfo='Europe/London',
        filters = {
              'match': 'and',
              'rules': [
                {
                  'field':'field_31',
                  'operator':'is after',
                  'value':'31/03/2018'
                },
                {
                  'field':'field_31',
                  'operator':'is before',
                  'value':'01/04/2019'
                }
              ]
            },
        page_limit=30,
        rows_per_page=1000
    )
```

However the same script without a filter fails  

```
from knackpy import Knack
kn = Knack( 
        obj='object_1',        
        app_id=XXXXXX',
        api_key='XXXXXX',
        tzinfo='Europe/London',
        page_limit=30,
        rows_per_page=1000
    )
```

And if I try a date in the filter that "is before" 07/06/2019 or any date after then it won't work and gives me the error above. Any combination prior to that works fine it doesn't seem to like late 2019 and any of 2020

```
from knackpy import Knack
kn = Knack( 
        obj='object_1',
        
        app_id='584202acb1d322842fe19657',
        api_key='82fee2f0-b8e6-11e6-9079-a7bdabe089f6',
        tzinfo='Europe/London',
        filters = {
              'match': 'and',
              'rules': [
                {
                  'field':'field_31',
                  'operator':'is after',
                  'value':'31/03/2019'
                },
                {
                  'field':'field_31',
                  'operator':'is before',
                  'value':'08/06/2019'
                }
              ]
            },
        page_limit=30,
        rows_per_page=1000
    )
```

Many Thanks

**Comment by johnclary** [comment]
@CatParky thanks for finding this bug. Would you be able to share a `JSON` export of the records from your Knack app which are encountering this error? If that's not possible, a `CSV` file which only includes the date fields would be help.

**Comment by johnclary** [comment]
@CatParky also, which operating system and Python version are you using?

**Comment by johnclary** [comment]
@CatParky closing this. Feel free to re-open with more info.
