### ISSUE TITLE
Knackpy.record is not working?

### ISSUE THREAD

**Issue by ilianapappi** [cityofaustin/knackpy#9]
``    record1 = {'id':'blabla,'field_496':'1'}
    
    response = Knack.record(
        record1,
        obj_key='object_23',    
        app_id='blabla',
        api_key='blabla',    
        method='update'
        )

I get the response:

AttributeError                            Traceback (most recent call last)
<ipython-input-11-07e6bf755a75> in <module>()
      4     record1 = {'id':str(i),'field_496':'1'}
      5 
----> 6     response = Knack.record(
      7         record1,
      8         obj_key='object_23',     #check which object in knack is the table you want to call here

AttributeError: type object 'Knack' has no attribute 'record'

**Comment by ilianapappi** [comment]
with Knack.record and knackpy.record i get exactly the same error (in the docs that's the way to update records so I don't know how to update them)
any help much appreciated, thanks

**Comment by johnclary** [comment]
hey there! thanks for using the module. i should be able to sort this out for you. would you verify which version of knackpy you have installed? `pip freeze` will do the trick

**Comment by ilianapappi** [comment]
Hi John!

Thank you so much for your answer! The version installed as I can see it with pip freeze is:
knackpy==0.0.5

I will be looking forward on how we could solve this issue 😄

**Comment by johnclary** [comment]
@ilianapappi the quick-start guide reflects version 0.0.11. You can do `pip install knackpy --upgrade` to pull the latest version. Then this should work for you:

```python
import knackpy

record1 = {'id':'blabla,'field_496':'1'}

response = knackpy.record(
    record1,
    obj_key=object_23,
    app_id= <app_id>,
    api_key=<api_key'>,
    method='update',
)
```

Let me know how it goes.

**Comment by johnclary** [comment]
@ilianapappi closing this issue. let me know if this needs further attention.
