### ISSUE TITLE
Support changing MAX_ROWS_PER_PAGE

### ISSUE THREAD

**Issue by aidanlister** [cityofaustin/knackpy#90]
Could we pass this in as a kwarg?

**Comment by johnclary** [comment]
@aidanlister i don't see why not. You probably gathered that at the moment we're setting to `1000` or the `record_limit`, whichever is lower. Can you spell out the use case for limiting max rows per page vs just using the overall `record_limit`?

**Comment by aidanlister** [comment]
It turns out this wasn't the problem, the problem was actually https://github.com/cityofaustin/knackpy/issues/91 ... so maybe there's not as much of a need to support this.

**Comment by johnclary** [comment]
Was hoping that was the case. Closed.
