### ISSUE TITLE
How to fill in connection field (one to many) from knackpy

### ISSUE THREAD

**Issue by rangganast** [cityofaustin/knackpy#97]
Hello
I have been using this knackpy package and it's awesome.
However I haven't found a way to fill in knack "connection field" when creating a row in object.
Any clue?

Thank you

**Comment by johnclary** [comment]
@rangganast sorry for the slow reply. Yes, this can be done. When you create or update a connection field, you need to use the record ID of the connected record.
For example, if `field_1` is your connection field, your payload would look like this:
```python
{
   "field_1": "5d65bad5614e4d001047b585"
}
```

If you connection field is a many-to-one, you can use a list of record IDs:
```python
{
   "field_1": ["5d65bad5614e4d001047b585",  "ad65badxe4d001047b585", "q9xcd65bad5614e4d0085"]
}
```

If you have doubts—take a look at the raw record data from Knack. You need to mirror this format.

This is not well documented, but see here:
 https://docs.knack.com/docs/view-based-post-for-inserting-a-connected-record

**Comment by rangganast** [comment]
Nice! Thank you so much.
